### ISSUE TITLE
Module stopped working

### ISSUE THREAD

**Issue by developeron29** [jprichardson/node-google#42]
Hey,
Thank you for this excellent module, Have been working for my app perfectly from the last 2 years.

But, few days ago, it stopped working and i am getting this error:

/Users/ayushnarula/Desktop/test.js:9
  for (var i = 0; i < res.links.length; ++i) {
                               ^

```
TypeError: Cannot read property 'length' of undefined
    at /Users/ayushnarula/Desktop/test.js:9:32
    at Request._callback (/Users/ayushnarula/node_modules/google/lib/google.js:57:7)
    at Request.self.callback (/Users/ayushnarula/node_modules/google/node_modules/request/main.js:122:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/Users/ayushnarula/node_modules/google/node_modules/request/main.js:661:16)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/Users/ayushnarula/node_modules/google/node_modules/request/main.js:623:14)
    at emitNone (events.js:72:20)  
```

Wondering if google had changed its html results structure

Thanks again,
Cheers

**Comment by Imadra** [comment]
Did you solve this issue?
