### ISSUE TITLE
Error in npm package on heroku.

### ISSUE THREAD

**Issue by tavrij** [jprichardson/node-google#50]
Hi
I'm beginner in git, nodejs and heroku.
Please give me a step by step instructions to install and use this package on heroku.

thanks.

**Comment by jprichardson** [comment]
Sorry, that's out of scope for this repo. I'd suggest starting out small with each tool and read tutorials on each one and attempt to learn how to apply it to your problem.

**Comment by tavrij** [comment]
I'm done this instructions completely:

1) Installing git, npm, heroku CLI

2) Deploying repository successfully on heroku

but in running the app, [it has error](https://gsnd.herokuapp.com/)

My sample code of index.js is this:

```
    var google = require('google')

google.resultsPerPage = 25
var nextCounter = 0

google('node.js best practices', function (err, res){
  if (err) console.error(err);
    var results = Array();
    if (res.links){
  for (var i = 0; i < res.links.length; ++i) {

    results.push(res.links[i]);
  }
   res.json(results);
              }else{
                res.json('[]');
              }

  if (nextCounter < 4) {
    nextCounter += 1
    if (res.next) res.next()
  }
})
```
this is the log file:

```
2017-01-28T03:49:37.418241+00:00 app[web.1]:     at emitTwo (events.js:100:13)
2017-01-28T03:49:37.418241+00:00 app[web.1]:     at Request.emit (events.js:185:7)
2017-01-28T03:49:37.418242+00:00 app[web.1]:     at Request.<anonymous> (/app/node_modules/request/request.js:1081:10)
2017-01-28T03:49:37.418243+00:00 app[web.1]:     at emitOne (events.js:90:13)
2017-01-28T03:49:37.418243+00:00 app[web.1]:     at Request.emit (events.js:182:7)
2017-01-28T03:49:37.418244+00:00 app[web.1]:     at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1001:12)
2017-01-28T03:49:37.418244+00:00 app[web.1]:     at IncomingMessage.g (events.js:273:16)
2017-01-28T03:49:37.548066+00:00 heroku[web.1]: State changed from starting to crashed
2017-01-28T03:49:37.519683+00:00 heroku[web.1]: Process exited with status 1
2017-01-28T07:09:18.620055+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=gsnd.herokuapp.com request_id=0343f938-0b2b-4d26-b1e1-dd4eaaed8ccb fwd="46.245.17.126" dyno= connect= service= status=503 bytes=
2017-01-28T07:09:29.624705+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=gsnd.herokuapp.com request_id=c5c76159-8f86-456c-b4da-c0b6cda0f0e6 fwd="46.245.17.126" dyno= connect= service= status=503 bytes=
Additional that this code runs successfully on runkit.com
```

Thanks

**Comment by jprichardson** [comment]
@tavrij - sorry, I don't use Heroku, so I don't know. Why not trying running that example script on your local machine to ensure it's not a problem with the example script?
